-module(cryptoapis_decode_raw_transaction_hex_ris).

-export([encode/1]).

-export_type([cryptoapis_decode_raw_transaction_hex_ris/0]).

-type cryptoapis_decode_raw_transaction_hex_ris() ::
    #{ 'locktime' := integer(),
       'transactionHash' := binary(),
       'vSize' := integer(),
       'version' := integer(),
       'vin' := list(),
       'vout' := list(),
       'weight' => integer(),
       'approximateFee' => binary(),
       'approximateMinimumRequiredFee' => binary(),
       'gasLimit' := binary(),
       'gasPaidForData' => binary(),
       'gasPrice' => binary(),
       'inputData' => binary(),
       'maxFeePerGas' => binary(),
       'maxFeePriorityPerGas' => binary(),
       'nonce' := integer(),
       'r' => binary(),
       'recipient' := binary(),
       's' => binary(),
       'sender' := binary(),
       'type' := integer(),
       'v' => binary(),
       'value' => binary(),
       'expiryHeight' := integer(),
       'overwintered' := boolean(),
       'saplinged' := boolean(),
       'valueBalance' := binary(),
       'versionGroupId' := binary()
     }.

encode(#{ 'locktime' := Locktime,
          'transactionHash' := TransactionHash,
          'vSize' := VSize,
          'version' := Version,
          'vin' := Vin,
          'vout' := Vout,
          'weight' := Weight,
          'approximateFee' := ApproximateFee,
          'approximateMinimumRequiredFee' := ApproximateMinimumRequiredFee,
          'gasLimit' := GasLimit,
          'gasPaidForData' := GasPaidForData,
          'gasPrice' := GasPrice,
          'inputData' := InputData,
          'maxFeePerGas' := MaxFeePerGas,
          'maxFeePriorityPerGas' := MaxFeePriorityPerGas,
          'nonce' := Nonce,
          'r' := R,
          'recipient' := Recipient,
          's' := S,
          'sender' := Sender,
          'type' := Type,
          'v' := V,
          'value' := Value,
          'expiryHeight' := ExpiryHeight,
          'overwintered' := Overwintered,
          'saplinged' := Saplinged,
          'valueBalance' := ValueBalance,
          'versionGroupId' := VersionGroupId
        }) ->
    #{ 'locktime' => Locktime,
       'transactionHash' => TransactionHash,
       'vSize' => VSize,
       'version' => Version,
       'vin' => Vin,
       'vout' => Vout,
       'weight' => Weight,
       'approximateFee' => ApproximateFee,
       'approximateMinimumRequiredFee' => ApproximateMinimumRequiredFee,
       'gasLimit' => GasLimit,
       'gasPaidForData' => GasPaidForData,
       'gasPrice' => GasPrice,
       'inputData' => InputData,
       'maxFeePerGas' => MaxFeePerGas,
       'maxFeePriorityPerGas' => MaxFeePriorityPerGas,
       'nonce' => Nonce,
       'r' => R,
       'recipient' => Recipient,
       's' => S,
       'sender' => Sender,
       'type' => Type,
       'v' => V,
       'value' => Value,
       'expiryHeight' => ExpiryHeight,
       'overwintered' => Overwintered,
       'saplinged' => Saplinged,
       'valueBalance' => ValueBalance,
       'versionGroupId' => VersionGroupId
     }.
